### ISSUE TITLE
Bad Response

### ISSUE THREAD

**Issue by DevPandaPro** [SamiUllah-dev/gpt_flutter#1]
While I'm trying review the code and application functionality, I faced an issue, I'm always getting bad response, i have attached the token that refer to OpenAI API but still, I'm getting same issue, is that anything I need to change

Need your help...

**Comment by samiullah-dev** [comment]
There might be some issue in you API please cross check the API as there might be some typo or something similar and if the problem still persists, show me your AIHandler class code with your API hidden.

**Comment by DevPandaPro** [comment]
>

**Comment by DevPandaPro** [comment]
> There might be some issue in you API please cross check the API as there might be some typo or something similar and if the problem still persists, show me your AIHandler class code with your API hidden.

I searched about the issue, I'm not sure about that but I think one of the requirements is to activate the billing method on OpenAI platform, is that true, or I can use the API without activating Billing method?

**Comment by samiullah-dev** [comment]
Go to OpenAI's site and navigate to the Billing section then check if your free trial is expired.

**Comment by DevPandaPro** [comment]
> Go to OpenAI's site and navigate to the Billing section then check if your free trial is expired.

Alright, thank you for your support...

**Comment by samiullah-dev** [comment]
No problem, happy to assist!
